# Generated by Django 6.0.6 on 2026-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=255, unique=True)),
                ('general_description', models.TextField(blank=True, null=True)),
                ('adult_description', models.TextField(blank=True, null=True)),
                ('baby_description', models.TextField(blank=True, null=True)),
                ('diet_lifestyle', models.TextField(blank=True, null=True)),
                ('microba_description', models.TextField(blank=True, null=True)),
                ('frx_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'metric'],
            },
        ),
        migrations.CreateModel(
            name='TaxonDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.CharField(max_length=255, unique=True)),
                ('phylum', models.CharField(blank=True, max_length=255, null=True)),
                ('associations', models.TextField(blank=True, null=True)),
                ('frx_description', models.TextField(blank=True, null=True)),
                ('th_description', models.TextField(blank=True, null=True)),
                ('baby_description', models.TextField(blank=True, null=True)),
                ('microba_description', models.TextField(blank=True, null=True)),
                ('unseenbio_description', models.TextField(blank=True, null=True)),
                ('daytwo_description', models.TextField(blank=True, null=True)),
                ('industry_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['organism'],
            },
        ),
    ]
