# Generated by Django 6.0.6 on 2026-06-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxondefinition',
            name='organism',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='taxondefinition',
            name='phylum',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
