# Generated by Django 6.0.6 on 2026-06-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_taxondefinition_organism_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricdefinition',
            options={'ordering': ['metric_name']},
        ),
        migrations.RenameField(
            model_name='metricdefinition',
            old_name='metric',
            new_name='metric_name',
        ),
        migrations.RemoveField(
            model_name='metricdefinition',
            name='adult_description',
        ),
        migrations.RemoveField(
            model_name='metricdefinition',
            name='baby_description',
        ),
        migrations.RemoveField(
            model_name='metricdefinition',
            name='diet_lifestyle',
        ),
        migrations.RemoveField(
            model_name='metricdefinition',
            name='frx_description',
        ),
        migrations.RemoveField(
            model_name='metricdefinition',
            name='general_description',
        ),
        migrations.RemoveField(
            model_name='metricdefinition',
            name='microba_description',
        ),
        migrations.RemoveField(
            model_name='metricdefinition',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
