# Generated by Django 6.0.6 on 2026-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_metricdefinition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='source_system',
            field=models.CharField(default='Adult Gut Microbiome', max_length=255),
        ),
    ]
