# Generated by Django 6.0.6 on 2026-06-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_metricdefinition_source_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='super_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='use_italics',
            field=models.BooleanField(default=False),
        ),
    ]
