# Generated by Django 6.0.6 on 2026-06-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_metricdefinition_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterotypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(default='adult_microbiome', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='adult_microbiome', max_length=100)),
                ('section_name', models.CharField(max_length=255)),
                ('super_category', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'section_name'],
                'unique_together': {('report_type', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='ReportMetricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='adult_microbiome', max_length=100)),
                ('category_title', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_percentage', models.BooleanField(default=False)),
                ('use_italics', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='knowledge.metricdefinition')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='knowledge.reportsection')),
            ],
            options={
                'ordering': ['display_order', 'metric_definition__metric_name'],
            },
        ),
    ]
