# Generated by Django 6.0.6 on 2026-06-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_enterotypedefinition_reportsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='knowledge.metricdefinition')),
            ],
            options={
                'ordering': ['synonym'],
                'constraints': [models.UniqueConstraint(fields=('metric_definition', 'synonym'), name='unique_metric_synonym')],
            },
        ),
        migrations.CreateModel(
            name='TaxonSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxon_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='knowledge.taxondefinition')),
            ],
            options={
                'ordering': ['synonym'],
                'constraints': [models.UniqueConstraint(fields=('taxon_definition', 'synonym'), name='unique_taxon_synonym')],
            },
        ),
    ]
