# Generated by Django 6.0.6 on 2026-06-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_metricsynonym_taxonsynonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricReferenceRangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='adult_microbiome', max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(blank=True, default='Lab CSV import', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_range_sets', to='knowledge.metricdefinition')),
            ],
            options={
                'ordering': ['metric_definition__metric_name', '-version'],
                'unique_together': {('metric_definition', 'report_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MetricReferenceRangeRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('category_title', models.CharField(blank=True, default='', max_length=255)),
                ('range_lower', models.FloatField(blank=True, null=True)),
                ('range_upper', models.FloatField(blank=True, null=True)),
                ('evaluation', models.CharField(blank=True, default='', max_length=255)),
                ('range_color', models.CharField(blank=True, default='', max_length=50)),
                ('range_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='knowledge.metricreferencerangeset')),
            ],
            options={
                'ordering': ['range_set', 'row_order'],
            },
        ),
    ]
