# Generated by Django 6.0.6 on 2026-06-29 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_metricreferencerangeset_metricreferencerangerow'),
        ('reports', '0006_missingmetricdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricReferenceRangeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='adult_microbiome', max_length=100)),
                ('detected_signature', models.TextField()),
                ('approved_signature', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_range_changes', to='knowledge.metricdefinition')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_range_changes', to='reports.report')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
