# Generated by Django 6.0.6 on 2026-06-30 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_metricreferencerangechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metricreferencerangechange',
            name='approved_range_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to='knowledge.metricreferencerangeset'),
        ),
        migrations.AddField(
            model_name='metricreferencerangechange',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reference_range_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
