# Generated by Django 6.0.6 on 2026-06-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_metricreferencerangechange_approved_range_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricreferencerangechange',
            name='proposed_rows',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
