# Generated by Django 6.0.6 on 2026-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_metricreferencerangechange_proposed_rows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmetrictemplate',
            options={'ordering': ['super_category_order', 'category_order', 'metric_order', 'display_order', 'metric_definition__metric_name']},
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='category_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='category_title_override',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='decimal_places',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='display_name_override',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='include_in_pdf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='legacy_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='legacy_range_template',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='metric_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='preserve_repeated_rows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='super_category_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportmetrictemplate',
            name='super_category_override',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
