from django.urls import path

from .views import (
    create_report,
    review_report,
    report_success,
    report_history,
    report_detail,
    missing_taxa_dashboard,
    missing_taxon_detail,
    mark_missing_taxon_resolved,
    create_taxon_definition_from_missing,
    missing_metrics_dashboard,
    missing_metric_detail,
    platform_dashboard,
    download_generated_pdf,
    download_processed_taxa_csv,
    download_original_metrics_csv,
    download_original_taxa_csv,
    download_processed_metrics_csv,
)

urlpatterns = [
    path(
        "",
        platform_dashboard,
        name="platform_dashboard",
    ),
    path(
        "new/",
        create_report,
        name="create_report",
    ),
    path(
        "<int:report_id>/review/",
        review_report,
        name="review_report",
    ),
    path(
        "<int:report_id>/success/",
        report_success,
        name="report_success",
    ),
    path(
        "history/",
        report_history,
        name="report_history",
    ),
    #taxa
    path(
        "missing-taxa/",
        missing_taxa_dashboard,
        name="missing_taxa_dashboard",
    ),
    path(
        "missing-taxa/<path:taxonomy_name>/resolve/",
        mark_missing_taxon_resolved,
        name="mark_missing_taxon_resolved",
    ),
    path(
        "missing-taxa/<path:taxonomy_name>/create-definition/",
        create_taxon_definition_from_missing,
        name="create_taxon_definition_from_missing",
    ),
    path(
        "missing-taxa/<path:taxonomy_name>/",
        missing_taxon_detail,
        name="missing_taxon_detail",
    ),
    #metrics
    path(
        "missing-metrics/",
        missing_metrics_dashboard,
        name="missing_metrics_dashboard",
    ),
    path(
        "missing-metrics/<path:metric_name>/",
        missing_metric_detail,
        name="missing_metric_detail",
    ),

    path(
        "<int:report_id>/download-pdf/",
        download_generated_pdf,
        name="download_generated_pdf",
    ),
    path(
        "<int:report_id>/download-processed-taxa/",
        download_processed_taxa_csv,
        name="download_processed_taxa_csv",
    ),
    path(
        "reports/<int:report_id>/download/processed-metrics/",
        download_processed_metrics_csv,
        name="download_processed_metrics_csv",
    ),
    path(
        "<int:report_id>/download-original-metrics/",
        download_original_metrics_csv,
        name="download_original_metrics_csv",
    ),
    path(
        "<int:report_id>/download-original-taxa/",
        download_original_taxa_csv,
        name="download_original_taxa_csv",
    ),
    path(
        "<int:report_id>/",
        report_detail,
        name="report_detail",
    ),
]
