# Generated by Django 6.0.6 on 2026-06-16 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(default='v1', max_length=50)),
                ('template_pdf', models.FileField(blank=True, null=True, upload_to='report_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['report_type', 'name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_id', models.CharField(db_index=True, max_length=100)),
                ('patient_name', models.CharField(max_length=255)),
                ('physician_name', models.CharField(max_length=255)),
                ('sampling_date', models.DateField(blank=True, null=True)),
                ('enterotype', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.reporttemplate')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.reporttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='generated_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_pdf', to='reports.report')),
            ],
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='reports.reporttype'),
        ),
        migrations.CreateModel(
            name='UploadedCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_metrics_csv', models.FileField(upload_to='uploads/original_metrics/')),
                ('original_taxa_csv', models.FileField(upload_to='uploads/original_taxa/')),
                ('processed_metrics_csv', models.FileField(blank=True, null=True, upload_to='uploads/processed_metrics/')),
                ('processed_taxa_csv', models.FileField(blank=True, null=True, upload_to='uploads/processed_taxa/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_csvs', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='MissingTaxonDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_name', models.CharField(max_length=255)),
                ('detected_abundance', models.FloatField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_taxa', to='reports.report')),
            ],
            options={
                'ordering': ['taxonomy_name'],
                'unique_together': {('report', 'taxonomy_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplate',
            unique_together={('report_type', 'name', 'version')},
        ),
    ]
