# Generated by Django 6.0.6 on 2026-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='enterotype',
            field=models.CharField(blank=True, choices=[('Bacteroides', 'Bacteroides'), ('Prevotella', 'Prevotella'), ('Ruminococcaceae', 'Ruminococcaceae'), ('Lachnospiraceae', 'Lachnospiraceae'), ('Bifidobacterium', 'Bifidobacterium'), ('Other', 'Other'), ('Enterobacteriaceae', 'Enterobacteriaceae')], max_length=120, null=True),
        ),
    ]
