# Generated by Django 6.0.6 on 2026-06-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_probiotic_species_color_report_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='processed_metrics_csv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/processed_metrics/'),
        ),
    ]
